name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build .\obonator --configuration Release --no-restore
    - name: Test
      run: dotnet test .\obonator --no-restore --verbosity normal
    - name: Publish with dotnet
      run: dotnet publish .\obonator --configuration Release --output build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          GITHUB_TOKEN: ${{ secrets.obonator }}
          BRANCH: gh-pages
          FOLDER: build/wwwroot
          CLEAN: true
